foo: foo version 10
spring:
  application:
    name: config-client
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitmq
    password: rabbitmq@cfhl@test
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
